/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Design;

/**
 *
 * @author asus
 */
public class Clipping extends javax.swing.JFrame {

    /**
     * Creates new form Clipping
     */
//     int x1, y1, x2, y2, x3, y3, degree, she, grid = 20, wSize = 480 /2;
//     float skala;
//     int XT,YT;
    
    int x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, d1, d2, d3, state;
    float scale;
    int wSize = 480 / 2, grid = 20;

   
    public Clipping() {
        initComponents();
        jScrollPane1.setViewportView(new Koordinat());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        pointX1 = new javax.swing.JTextField();
        pointY1 = new javax.swing.JTextField();
        pointY2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        addPoint = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        pointX2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        xa1 = new javax.swing.JTextField();
        ya1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        xb1 = new javax.swing.JTextField();
        yb1 = new javax.swing.JTextField();
        yb2 = new javax.swing.JTextField();
        xb2 = new javax.swing.JTextField();
        ya2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        xa2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        xa3 = new javax.swing.JTextField();
        ya3 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        xb3 = new javax.swing.JTextField();
        yb3 = new javax.swing.JTextField();
        addLine = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        x1_rect = new javax.swing.JTextField();
        y1_rect = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        x2_rect = new javax.swing.JTextField();
        y3_rect = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        y2_rect = new javax.swing.JTextField();
        x3_rect = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        width1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        width2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        width3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        height1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        height2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        height3 = new javax.swing.JTextField();
        addRect = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        xt_a1 = new javax.swing.JTextField();
        yt_a1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        xt_b1 = new javax.swing.JTextField();
        yt_b1 = new javax.swing.JTextField();
        yt_c1 = new javax.swing.JTextField();
        xt_c1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        xt_a2 = new javax.swing.JTextField();
        yt_a2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        xt_b2 = new javax.swing.JTextField();
        yt_b2 = new javax.swing.JTextField();
        xt_c2 = new javax.swing.JTextField();
        yt_c2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        xt_a3 = new javax.swing.JTextField();
        yt_a3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        xt_b3 = new javax.swing.JTextField();
        yt_b3 = new javax.swing.JTextField();
        yt_c3 = new javax.swing.JTextField();
        addTriangle = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        xt_c3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        xmin = new javax.swing.JTextField();
        xmax = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ymin = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ymax = new javax.swing.JTextField();
        addClip = new javax.swing.JButton();
        clip = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 700));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(90, 100));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel38.setFont(new java.awt.Font("Instruction", 1, 55)); // NOI18N
        jLabel38.setText("CLIPPING");

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel32.setText("Point A1");

        pointY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointY1ActionPerformed(evt);
            }
        });

        pointY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointY2ActionPerformed(evt);
            }
        });

        jLabel33.setText("Point A2");

        addPoint.setText("Add Point");
        addPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPointActionPerformed(evt);
            }
        });

        jLabel34.setText("X2");

        jLabel35.setText("Y2");

        jLabel36.setText("X1");

        jLabel37.setText("Y1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pointY1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel32)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pointX1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pointX2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                    .addComponent(pointY2))))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(addPoint)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel32)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pointX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pointY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(pointX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pointY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(addPoint)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Point", jPanel6);

        jLabel26.setText("Point A1");

        ya1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ya1ActionPerformed(evt);
            }
        });

        jLabel27.setText("Point B1");

        yb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yb1ActionPerformed(evt);
            }
        });

        yb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yb2ActionPerformed(evt);
            }
        });

        ya2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ya2ActionPerformed(evt);
            }
        });

        jLabel28.setText("Point B2");

        jLabel29.setText("Point A2");

        jLabel30.setText("Point A3");

        ya3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ya3ActionPerformed(evt);
            }
        });

        jLabel31.setText("Point B3");

        yb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yb3ActionPerformed(evt);
            }
        });

        addLine.setText("Add Line");
        addLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yb1)
                            .addComponent(ya1)
                            .addComponent(xb1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(xa1))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yb2)
                            .addComponent(ya2)
                            .addComponent(xb2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel28))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(xa2))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ya3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(xa3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(yb3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(xb3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(addLine)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ya1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ya2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(xa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ya3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(addLine)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Line", jPanel4);

        jLabel10.setText("X1");

        y1_rect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y1_rectActionPerformed(evt);
            }
        });

        jLabel11.setText("X2");

        y3_rect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y3_rectActionPerformed(evt);
            }
        });

        jLabel12.setText("X3");

        y2_rect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y2_rectActionPerformed(evt);
            }
        });

        jLabel13.setText("Y3");

        jLabel14.setText("Y1");

        jLabel15.setText("Y2");

        jLabel16.setText("Width1");

        width1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                width1ActionPerformed(evt);
            }
        });

        jLabel17.setText("Width2");

        width2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                width2ActionPerformed(evt);
            }
        });

        jLabel18.setText("Width3");

        width3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                width3ActionPerformed(evt);
            }
        });

        jLabel19.setText("Height1");

        height1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                height1ActionPerformed(evt);
            }
        });

        jLabel20.setText("Height2");

        height2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                height2ActionPerformed(evt);
            }
        });

        jLabel21.setText("Height3");

        height3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                height3ActionPerformed(evt);
            }
        });

        addRect.setText("Add Rectangle");
        addRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addRect)
                            .addComponent(jLabel19)
                            .addComponent(height1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14)
                                    .addComponent(y1_rect, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(y2_rect, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(x1_rect, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(64, 64, 64)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(height2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                            .addComponent(x2_rect, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(width2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(width3, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(y3_rect, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(x3_rect, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                                            .addComponent(height3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(width1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x1_rect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x2_rect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x3_rect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(y3_rect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(y1_rect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(y2_rect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(width3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(width2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(width1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20))
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(height2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(height1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(height3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(addRect)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Rectangle", jPanel5);

        jLabel1.setText("Point A1");

        yt_a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yt_a1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Point B1");

        yt_b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yt_b1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Point C1");

        jLabel4.setText("Point A2");

        yt_a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yt_a2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Point B2");

        yt_b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yt_b2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Point A3");

        yt_a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yt_a3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Point B3");

        yt_b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yt_b3ActionPerformed(evt);
            }
        });

        addTriangle.setText("Add Triangle");
        addTriangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTriangleActionPerformed(evt);
            }
        });

        jLabel39.setText("Pont C3");

        jLabel9.setText("Point C2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yt_b1)
                            .addComponent(xt_c1)
                            .addComponent(yt_a1)
                            .addComponent(xt_b1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(xt_a1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(yt_c1))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yt_b2)
                                    .addComponent(xt_c2)
                                    .addComponent(yt_c2)
                                    .addComponent(yt_a2)
                                    .addComponent(xt_b2)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(xt_a2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(30, 30, 30))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(xt_a3, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(yt_a3, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(xt_b3, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(yt_b3, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(yt_c3, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(jLabel39)
                            .addComponent(xt_c3))
                        .addGap(52, 52, 52))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(addTriangle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xt_a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yt_a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xt_b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xt_a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xt_a3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yt_a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yt_a3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xt_b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xt_b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yt_b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yt_b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yt_b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xt_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xt_c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xt_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yt_c2)
                            .addComponent(yt_c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yt_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addTriangle)
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Triangle", jPanel3);

        jLabel22.setText("X Min");

        jLabel23.setText("X Max");

        jLabel24.setText("Y Min");

        jLabel25.setText("Y Max");

        addClip.setText("Add Clip Area");
        addClip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClipActionPerformed(evt);
            }
        });

        clip.setText("Clip");
        clip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xmin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ymin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(ymax, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(clip))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(xmax, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(addClip))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addClip))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ymin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ymax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clip))
                .addContainerGap())
        );

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clear)
                .addGap(18, 18, 18)
                .addComponent(back)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel38)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear)
                    .addComponent(back))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yt_a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yt_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yt_a1ActionPerformed

    private void yt_b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yt_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yt_b1ActionPerformed

    private void yt_a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yt_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yt_a2ActionPerformed

    private void yt_b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yt_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yt_b2ActionPerformed

    private void yt_a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yt_a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yt_a3ActionPerformed

    private void yt_b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yt_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yt_b3ActionPerformed

    private void ya1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ya1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ya1ActionPerformed

    private void yb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yb1ActionPerformed

    private void yb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yb2ActionPerformed

    private void ya2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ya2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ya2ActionPerformed

    private void ya3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ya3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ya3ActionPerformed

    private void yb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yb3ActionPerformed

    private void pointY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pointY1ActionPerformed

    private void pointY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointY2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pointY2ActionPerformed

    private void height3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_height3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_height3ActionPerformed

    private void height2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_height2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_height2ActionPerformed

    private void height1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_height1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_height1ActionPerformed

    private void width3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_width3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_width3ActionPerformed

    private void width2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_width2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_width2ActionPerformed

    private void width1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_width1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_width1ActionPerformed

    private void y2_rectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y2_rectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y2_rectActionPerformed

    private void y3_rectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y3_rectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y3_rectActionPerformed

    private void y1_rectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y1_rectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y1_rectActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new TitikBidang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_clearActionPerformed

    private void addPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPointActionPerformed
        // TODO add your handling code here:
        try {
            x1 = Integer.parseInt(pointX1.getText());
            y1 = Integer.parseInt(pointY1.getText());
            x2 = Integer.parseInt(pointX2.getText());
            y2 = Integer.parseInt(pointY2.getText());
            jScrollPane1.setViewportView(new Koordinat(x1, y1, x2, y2, 1));
            state = 1;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_addPointActionPerformed

    private void addClipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClipActionPerformed
        // TODO add your handling code here:
        int xMin = Integer.parseInt(xmin.getText());
        int xMax = Integer.parseInt(xmax.getText());
        int yMin = Integer.parseInt(ymin.getText());
        int yMax = Integer.parseInt(ymax.getText());
        int c[] = {xMin, xMax, yMin, yMax};
        
        
        if (state == 1) {//point
            try {
                x1 = Integer.parseInt(pointX1.getText());
                y1 = Integer.parseInt(pointY1.getText());
                x2 = Integer.parseInt(pointX2.getText());
                y2 = Integer.parseInt(pointY2.getText());
                int x[] = {x1, x2};
                int y[] = {y1, y2};
                jScrollPane1.setViewportView(new Clip(x, y, c, 20, 1));
            } catch (Exception e) {
            }
        }
        if (state == 2) {//line
            try {
                x1 = Integer.parseInt(xa1.getText());
                y1 = Integer.parseInt(ya1.getText());
                x2 = Integer.parseInt(xb1.getText());
                y2 = Integer.parseInt(yb2.getText());
                x3 = Integer.parseInt(xa2.getText());
                y3 = Integer.parseInt(ya2.getText());
                x4 = Integer.parseInt(xb2.getText());
                y4 = Integer.parseInt(yb2.getText());
                x5 = Integer.parseInt(xa3.getText());
                y5 = Integer.parseInt(ya3.getText());
                x6 = Integer.parseInt(xb3.getText());
                y6 = Integer.parseInt(yb3.getText());
                int x[] = {x1, x2, x3, x4, x5, x6};
                int y[] = {y1, y2, y3, y4, y5, y6};
                jScrollPane1.setViewportView(new Clip(x, y, c, 21, 1));
            } catch (Exception e) {
            }
        }
        if (state == 3) {//rectangle
            try {
                x1 = Integer.parseInt(x1_rect.getText());
                y1 = Integer.parseInt(y1_rect.getText());
                x2 = Integer.parseInt(width1.getText());//w1
                y2 = Integer.parseInt(height1.getText());//h1
                x3 = Integer.parseInt(x2_rect.getText());
                y3 = Integer.parseInt(y2_rect.getText());
                x4 = Integer.parseInt(width2.getText());//w2
                y4 = Integer.parseInt(height2.getText());//h2
                x5 = Integer.parseInt(x3_rect.getText());
                y5 = Integer.parseInt(y3_rect.getText());
                x6 = Integer.parseInt(width3.getText());//w3
                y6 = Integer.parseInt(height3.getText());//h3
                int x[] = {x1, x2, x3, x4, x5, x6};
                int y[] = {y1, y2, y3, y4, y5, y6};
                jScrollPane1.setViewportView(new Clip(x, y, c, 22, 1));
            } catch (Exception e) {
            }
        }
        if (state == 4) {//triagle
            try {
                x1 = Integer.parseInt(xt_a1.getText());
                x2 = Integer.parseInt(xt_b1.getText());
                x3 = Integer.parseInt(xt_c1.getText());
                y1 = Integer.parseInt(yt_a1.getText());
                y2 = Integer.parseInt(yt_b1.getText());
                y3 = Integer.parseInt(yt_c1.getText());
                x4 = Integer.parseInt(xt_a2.getText());
                x5 = Integer.parseInt(xt_b2.getText());
                x6 = Integer.parseInt(xt_c2.getText());
                y4 = Integer.parseInt(yt_a2.getText());
                y5 = Integer.parseInt(yt_b2.getText());
                y6 = Integer.parseInt(yt_c2.getText());
                int x7 = Integer.parseInt(xt_a3.getText());
                int x8 = Integer.parseInt(xt_b3.getText());
                int x9 = Integer.parseInt(xt_c3.getText());
                int y7 = Integer.parseInt(yt_a3.getText());
                int y8 = Integer.parseInt(yt_b3.getText());
                int y9 = Integer.parseInt(yt_c3.getText());
                int x[] = {x1 * grid + wSize, x2 * grid + wSize, x3 * grid + wSize, x4 * grid + wSize, x5 * grid + wSize,
                    x6 * grid + wSize, x7 * grid + wSize, x8 * grid + wSize, x9 * grid + wSize};
                int y[] = {wSize - grid * y1, wSize - grid * y2, wSize - grid * y3, wSize - grid * y4, wSize - grid * y5,
                    wSize - grid * y6, wSize - grid * y7, wSize - grid * y8, wSize - grid * y9};
                jScrollPane1.setViewportView(new Clip(x, y, c, 23, 1));
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_addClipActionPerformed

    private void clipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clipActionPerformed
        // TODO add your handling code here:
        int xMin = Integer.parseInt(xmin.getText());
        int xMax = Integer.parseInt(xmax.getText());
        int yMin = Integer.parseInt(ymin.getText());
        int yMax = Integer.parseInt(ymax.getText());
        int c[] = {xMin, xMax, yMin, yMax};
        
        
        if (state == 1) {//point
            try {
                x1 = Integer.parseInt(pointX1.getText());
                y1 = Integer.parseInt(pointY1.getText());
                x2 = Integer.parseInt(pointX2.getText());
                y2 = Integer.parseInt(pointY2.getText());
                int x[] = {x1, x2};
                int y[] = {y1, y2};
                jScrollPane1.setViewportView(new Clip(x, y, c, 20, 2));
            } catch (Exception e) {
            }
        }
        if (state == 2) {//line
            try {
                x1 = Integer.parseInt(xa1.getText());
                y1 = Integer.parseInt(ya1.getText());
                x2 = Integer.parseInt(xb1.getText());
                y2 = Integer.parseInt(yb2.getText());
                x3 = Integer.parseInt(xa2.getText());
                y3 = Integer.parseInt(ya2.getText());
                x4 = Integer.parseInt(xb2.getText());
                y4 = Integer.parseInt(yb2.getText());
                x5 = Integer.parseInt(xa3.getText());
                y5 = Integer.parseInt(ya3.getText());
                x6 = Integer.parseInt(xb3.getText());
                y6 = Integer.parseInt(yb3.getText());
                int x[] = {x1, x2, x3, x4, x5, x6};
                int y[] = {y1, y2, y3, y4, y5, y6};
                jScrollPane1.setViewportView(new Clip(x, y, c, 21, 2));
            } catch (Exception e) {
            }
        }
        if (state == 3) {//rectangle
            try {
                x1 = Integer.parseInt(x1_rect.getText());
                y1 = Integer.parseInt(y1_rect.getText());
                x2 = Integer.parseInt(width1.getText());//w1
                y2 = Integer.parseInt(height1.getText());//h1
                x3 = Integer.parseInt(x2_rect.getText());
                y3 = Integer.parseInt(y2_rect.getText());
                x4 = Integer.parseInt(width2.getText());//w2
                y4 = Integer.parseInt(height2.getText());//h2
                x5 = Integer.parseInt(x3_rect.getText());
                y5 = Integer.parseInt(y3_rect.getText());
                x6 = Integer.parseInt(width3.getText());//w3
                y6 = Integer.parseInt(height3.getText());//h3
                int x[] = {x1, x2, x3, x4, x5, x6};
                int y[] = {y1, y2, y3, y4, y5, y6};
                jScrollPane1.setViewportView(new Clip(x, y, c, 22, 2));
            } catch (Exception e) {
            }
        }
        if (state == 4) {//triagle
            try {
                x1 = Integer.parseInt(xt_a1.getText());
                x2 = Integer.parseInt(xt_b1.getText());
                x3 = Integer.parseInt(xt_c1.getText());
                y1 = Integer.parseInt(yt_a1.getText());
                y2 = Integer.parseInt(yt_b1.getText());
                y3 = Integer.parseInt(yt_c1.getText());
                x4 = Integer.parseInt(xt_a2.getText());
                x5 = Integer.parseInt(xt_b2.getText());
                x6 = Integer.parseInt(xt_c2.getText());
                y4 = Integer.parseInt(yt_a2.getText());
                y5 = Integer.parseInt(yt_b2.getText());
                y6 = Integer.parseInt(yt_c2.getText());
                int x7 = Integer.parseInt(xt_a3.getText());
                int x8 = Integer.parseInt(xt_b3.getText());
                int x9 = Integer.parseInt(xt_c3.getText());
                int y7 = Integer.parseInt(yt_a3.getText());
                int y8 = Integer.parseInt(yt_b3.getText());
                int y9 = Integer.parseInt(yt_c3.getText());
                int x[] = {x1 * grid + wSize, x2 * grid + wSize, x3 * grid + wSize, x4 * grid + wSize, x5 * grid + wSize,
                    x6 * grid + wSize, x7 * grid + wSize, x8 * grid + wSize, x9 * grid + wSize};
                int y[] = {wSize - grid * y1, wSize - grid * y2, wSize - grid * y3, wSize - grid * y4, wSize - grid * y5,
                    wSize - grid * y6, wSize - grid * y7, wSize - grid * y8, wSize - grid * y9};
                jScrollPane1.setViewportView(new Clip(x, y, c, 23, 2));
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_clipActionPerformed

    private void addLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLineActionPerformed
        // TODO add your handling code here:
        try {
                x1 = Integer.parseInt(xa1.getText());
                y1 = Integer.parseInt(ya1.getText());
                x2 = Integer.parseInt(xb1.getText());
                y2 = Integer.parseInt(yb2.getText());
                x3 = Integer.parseInt(xa2.getText());
                y3 = Integer.parseInt(ya2.getText());
                x4 = Integer.parseInt(xb2.getText());
                y4 = Integer.parseInt(yb2.getText());
                x5 = Integer.parseInt(xa3.getText());
                y5 = Integer.parseInt(ya3.getText());
                x6 = Integer.parseInt(xb3.getText());
                y6 = Integer.parseInt(yb3.getText());
                int x[] = {x1, x2, x3, x4, x5, x6};
                int y[] = {y1, y2, y3, y4, y5, y6};
                jScrollPane1.setViewportView(new Clip(x, y, 21));
            } catch (Exception e) {
            }
        state = 2;
        
    }//GEN-LAST:event_addLineActionPerformed

    private void addRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRectActionPerformed
        // TODO add your handling code here:
        try {
                x1 = Integer.parseInt(x1_rect.getText());
                y1 = Integer.parseInt(y1_rect.getText());
                x2 = Integer.parseInt(width1.getText());//w1
                y2 = Integer.parseInt(height1.getText());//h1
                x3 = Integer.parseInt(x2_rect.getText());
                y3 = Integer.parseInt(y2_rect.getText());
                x4 = Integer.parseInt(width2.getText());//w2
                y4 = Integer.parseInt(height2.getText());//h2
                x5 = Integer.parseInt(x3_rect.getText());
                y5 = Integer.parseInt(y3_rect.getText());
                x6 = Integer.parseInt(width3.getText());//w3
                y6 = Integer.parseInt(height3.getText());//h3
                int x[] = {x1, x2, x3, x4, x5, x6};
                int y[] = {y1, y2, y3, y4, y5, y6};
                jScrollPane1.setViewportView(new Clip(x, y, 22));
            } catch (Exception e) {
            }
        state = 3;
    }//GEN-LAST:event_addRectActionPerformed

    private void addTriangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTriangleActionPerformed
        // TODO add your handling code here:
        try {
                x1 = Integer.parseInt(xt_a1.getText());
                x2 = Integer.parseInt(xt_b1.getText());
                x3 = Integer.parseInt(xt_c1.getText());
                y1 = Integer.parseInt(yt_a1.getText());
                y2 = Integer.parseInt(yt_b1.getText());
                y3 = Integer.parseInt(yt_c1.getText());
                x4 = Integer.parseInt(xt_a2.getText());
                x5 = Integer.parseInt(xt_b2.getText());
                x6 = Integer.parseInt(xt_c2.getText());
                y4 = Integer.parseInt(yt_a2.getText());
                y5 = Integer.parseInt(yt_b2.getText());
                y6 = Integer.parseInt(yt_c2.getText());
                int x7 = Integer.parseInt(xt_a3.getText());
                int x8 = Integer.parseInt(xt_b3.getText());
                int x9 = Integer.parseInt(xt_c3.getText());
                int y7 = Integer.parseInt(yt_a3.getText());
                int y8 = Integer.parseInt(yt_b3.getText());
                int y9 = Integer.parseInt(yt_c3.getText());
                int x[] = {x1 * grid + wSize, x2 * grid + wSize, x3 * grid + wSize, x4 * grid + wSize, x5 * grid + wSize,
                    x6 * grid + wSize, x7 * grid + wSize, x8 * grid + wSize, x9 * grid + wSize};
                int y[] = {wSize - grid * y1, wSize - grid * y2, wSize - grid * y3, wSize - grid * y4, wSize - grid * y5,
                    wSize - grid * y6, wSize - grid * y7, wSize - grid * y8, wSize - grid * y9};
                jScrollPane1.setViewportView(new Clip(x, y, 23));
            } catch (Exception e) {
            }
        state = 4;
    }//GEN-LAST:event_addTriangleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new TitikBidang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clipping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clipping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clipping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clipping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clipping().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClip;
    private javax.swing.JButton addLine;
    private javax.swing.JButton addPoint;
    private javax.swing.JButton addRect;
    private javax.swing.JButton addTriangle;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton clip;
    private javax.swing.JTextField height1;
    private javax.swing.JTextField height2;
    private javax.swing.JTextField height3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField pointX1;
    private javax.swing.JTextField pointX2;
    private javax.swing.JTextField pointY1;
    private javax.swing.JTextField pointY2;
    private javax.swing.JTextField width1;
    private javax.swing.JTextField width2;
    private javax.swing.JTextField width3;
    private javax.swing.JTextField x1_rect;
    private javax.swing.JTextField x2_rect;
    private javax.swing.JTextField x3_rect;
    private javax.swing.JTextField xa1;
    private javax.swing.JTextField xa2;
    private javax.swing.JTextField xa3;
    private javax.swing.JTextField xb1;
    private javax.swing.JTextField xb2;
    private javax.swing.JTextField xb3;
    private javax.swing.JTextField xmax;
    private javax.swing.JTextField xmin;
    private javax.swing.JTextField xt_a1;
    private javax.swing.JTextField xt_a2;
    private javax.swing.JTextField xt_a3;
    private javax.swing.JTextField xt_b1;
    private javax.swing.JTextField xt_b2;
    private javax.swing.JTextField xt_b3;
    private javax.swing.JTextField xt_c1;
    private javax.swing.JTextField xt_c2;
    private javax.swing.JTextField xt_c3;
    private javax.swing.JTextField y1_rect;
    private javax.swing.JTextField y2_rect;
    private javax.swing.JTextField y3_rect;
    private javax.swing.JTextField ya1;
    private javax.swing.JTextField ya2;
    private javax.swing.JTextField ya3;
    private javax.swing.JTextField yb1;
    private javax.swing.JTextField yb2;
    private javax.swing.JTextField yb3;
    private javax.swing.JTextField ymax;
    private javax.swing.JTextField ymin;
    private javax.swing.JTextField yt_a1;
    private javax.swing.JTextField yt_a2;
    private javax.swing.JTextField yt_a3;
    private javax.swing.JTextField yt_b1;
    private javax.swing.JTextField yt_b2;
    private javax.swing.JTextField yt_b3;
    private javax.swing.JTextField yt_c1;
    private javax.swing.JTextField yt_c2;
    private javax.swing.JTextField yt_c3;
    // End of variables declaration//GEN-END:variables
}
